name: ci

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: sarahvenus/20201201@v1
      -
        name: Set up Docker Buildx
        uses: sarahvenus/20201201@v1
      -
        name: Login to DockerHub
        uses: sarahvenus/20201201@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: sarahvenus/20201201@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: user/app:latest
